site_name: HydraxMPM
site_description: Documentation for the HydraxMPM.
site_author: Retief Lubbe

repo_url: https://github.com/GrainLearning/HydraxMPM
repo_name: GrainLearning/HydraxMPM

nav:
  - 'index.md'
  - Basic usage: usage/index.md
  - API:
      - Config: api/config.md
    # - Particles: api/particles.md
    # - Shapefunctions: api/shapefunctions.md
  # - Examples: 
    # - Two sphere impact: examples/two_sphere_impact.md
    # - Solvers: api/solvers.md
    # - Shape functions: api/shapefunctions.md
  #   - Materials: api/materials.md
  #   - Math utils: api/math.md
  # - About: about.md

strict: true  # Don't allow warnings during the build process


watch:
  - hydraxmpm

extra_css:
  - _static/extra.css

theme:
    name: material
    palette:
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      accent: custom
      features:
        - navigation.sections
        - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [hydraxmpm,examples]
          options:
            docstring_section_style: list
            # signature_crossrefs: true
            show_bases: false
            show_symbol_type_heading: true
            # ignore_init_summary: true
            # trim_doctest_flags: true
            # relative_crossrefs: true
            # show_docstring_modules: false
          # rendering:
            # show_root_full_path: true  # display "optimistix.asdf" not just "asdf"
            # show_if_no_docstring: false
            # show_signature_annotations: false
            show_source: false  # don't include source code
            members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
            heading_level: 4
            # docstring_section_style: list
          #   show_if_no_docstring: true
          #   show_source: false  # don't include source code
          #   heading_level: 4

            # selection:
            #     inherited_members: true  # Allow looking up inherited methods
            # rendering:
            #     show_root_heading: true  # actually display anything at all...
            #     show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
            #     show_signature_annotations: true
            #     members_order: source  # order methods according to their order of definition in the source code, not alphabetical order


# Ideas about documentations
# Create a section on termonolody?
## stacks...