[tool.poetry]
name = "pymudokon"
version = "0.1.0"
description = ""
authors = ["Retief Lubbe <retieflubbe@outlook.com>"]
readme = "README.md"
packages = [
    { include = "pymudokon" }
]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
jax = {extras = ["cpu"], version = "^0.4.28"}
typing-extensions = "^4.11.0" # type hinting of python 3.12
optax = "^0.2.2" # optimizers for return mapping, element benchmarks etc.
flax = "^0.8.4" # uses dataclass utilities for jax
chex = "^0.1.86"
optimistix = "^0.0.7"
extensysplots = "^1.0.2"
scienceplots = "^2.1.1"


[tool.poetry.group.gpu.dependencies]
jax = {extras = ["cuda12"], version = "^0.4.28"} # gpu version of Jax


[tool.poetry.group.visuals.dependencies]
ipykernel = "^6.29.4"
matplotlib = "^3.9.0"
jupyter = "^1.0.0"
imageio = "^2.34.1"
trame = "^3.6.0"
ipywidgets = "^8.1.2"
trame-jupyter-extension = "^2.1.0"
jupyterlab = ">=3"
jupyter-server-proxy = "^4.1.2"
pyvista = {extras = ["jupyter"], version = "^0.43.8"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.3"
pytest = "^7.1.3"
black = "^24.4.0"
pyperf = "^2.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



[tool.ruff.lint.isort]
combine-as-imports = true
extra-standard-library = ["typing_extensions"]
lines-after-imports = 2
order-by-type = false

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I001",  # isort
]
ignore = [
    "C901",  # too complex
    "W191",  # indentation contains tabs
    "E741",  # ambiguous variable name
    "N806", # argument name should be lowercase
    "N803", # argument name should be lowercase
]
fixable = ["I001", "F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"