[tool.poetry]
name = "pymudokon"
version = "0.1.0"
description = ""
authors = ["Retief Lubbe <retieflubbe@outlook.com>"]
readme = "README.md"
packages = [
    { include = "pymudokon" }
]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
pyvista = {extras = ["jupyter"], version = "^0.43.8"}
ruff = "^0.4.3"
jax = {extras = ["cpu"], version = "^0.4.28"}
typing-extensions = "^4.11.0"
jupyter = "^1.0.0"
imageio = "^2.34.1"
trame = "^3.6.0"
ipywidgets = "^8.1.2"
trame-jupyter-extension = "^2.1.0"
jupyterlab = ">=3"
jupyter-server-proxy = "^4.1.2"
xarray = {extras = ["vis"], version = "^2024.5.0"}
matplotlib = "^3.9.0"
optax = "^0.2.2"
jaxopt = "^0.8.3"

[tool.poetry.group.gpu.dependencies]
jax = {extras = ["cuda12"], version = "^0.4.28"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
ipykernel = "^6.29.4"
black = "^24.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 120


[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "N",  # PEP8 naming convetions
    "D"  # pydocstyle
]
ignore = [
    "C901",  # too complex
    "W191",  # indentation contains tabs

    "N806", # argument name should be lowercase
    "N803", # argument name should be lowercase
]


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"