[tool.poetry]
name = "pymudokon"
version = "0.1.0"
description = ""
authors = ["Retief Lubbe <retieflubbe@outlook.com>"]
readme = "README.md"
packages = [
    { include = "pymudokon" }
]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
pyvista = "^0.43.5"
ruff = "^0.4.3"
jax = {extras = ["cpu"], version = "^0.4.28"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
ipykernel = "^6.29.4"
black = "^24.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "N",  # PEP8 naming convetions
    "D"  # pydocstyle
]
ignore = [
    "C901",  # too complex
    "W191",  # indentation contains tabs

    "N806", # argument name should be lowercase
    "N803", # argument name should be lowercase
]

[tool.ruff.lint.pydocstyle]
convention = "google"

